version: "3.9"

services:
  app:
    build: .
    container_name: acs_app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/taskdb
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: acs_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
