spring.application.name=file-sharing-app
server.port=7070
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:4040/file-sharing
spring.datasource.username=filesharinguser
spring.datasource.password=filesharingpass
spring.jpa.hibernate.ddl-auto=update

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Cloudflare R2 Storage Configuration
r2.access_key=f3c2d932446b2a7672b78e4089e4ca8e
r2.secret_token=27b60100f0a992fe7604402afe9ffa5bb9e2577955de4f700f2b8fd4a385f22f
r2.account_id=d7d3df16effbecb47fa4723697c4b581
r2.main_bucket_name=the-garage-provider-bucket
r2.public_domain=https://pub-e14a1d746f574558999492bb700faa0b.r2.dev

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.resolve-lazily=false
