# Generated by Django 6.0 on 2025-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RON', 'RON')], default='MDL', max_length=3),
        ),
    ]
