# Generated by Django 6.0 on 2025-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='eur',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='ron',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
