# Generated by Django 6.0 on 2025-12-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_cartitem_price'),
        ('product', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='wishlists', to='product.product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customer.profile')),
            ],
        ),
    ]
