# Generated by Django 6.0 on 2026-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('recipient', 'event_key')},
        ),
    ]
