# Generated by Django 6.0 on 2026-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_items_summary_orderitem_age_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('MDL', 'MDL'), ('EUR', 'EUR'), ('USD', 'USD'), ('RON', 'RON')], default='MDL', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Rata față de MDL la momentul comenzii', max_digits=10),
            preserve_default=False,
        ),
    ]
