# Generated by Django 6.0.1 on 2026-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_currency_order_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'În procesare'), ('processed', 'Procesată'), ('cancelled', 'Anulată')], default='new', max_length=20),
        ),
    ]
